const citites: City[] = [
  {
    country: "Argentina",
    name: "Buenos Aires",
    latitude: -34.6037,
    longitude: -58.3816,
    countryCode: "AR",
  },
  {
    country: "Australia",
    name: "Canberra",
    latitude: -35.2809,
    longitude: 149.13,
    countryCode: "AU",
  },
  {
    country: "Brasil",
    name: "Brasilia",
    latitude: -15.8267,
    longitude: -47.9218,
    countryCode: "BR",
  },
  {
    country: "Canadá",
    name: "Ottawa",
    latitude: 45.4215,
    longitude: -75.6972,
    countryCode: "CA",
  },
  {
    country: "China",
    name: "Beijing",
    latitude: 39.9042,
    longitude: 116.4074,
    countryCode: "CN",
  },
  {
    country: "Egipto",
    name: "El Cairo",
    latitude: 30.0444,
    longitude: 31.2357,
    countryCode: "EG",
  },
  {
    country: "Francia",
    name: "París",
    latitude: 48.8566,
    longitude: 2.3522,
    countryCode: "FR",
  },
  {
    country: "Alemania",
    name: "Berlín",
    latitude: 52.52,
    longitude: 13.405,
    countryCode: "DE",
  },
  {
    country: "India",
    name: "Nueva Delhi",
    latitude: 28.6139,
    longitude: 77.209,
    countryCode: "IN",
  },
  {
    country: "Italia",
    name: "Roma",
    latitude: 41.9028,
    longitude: 12.4964,
    countryCode: "IT",
  },
  {
    country: "Japón",
    name: "Tokio",
    latitude: 35.6895,
    longitude: 139.6917,
    countryCode: "JP",
  },
  {
    country: "México",
    name: "Ciudad de México",
    latitude: 19.4326,
    longitude: -99.1332,
    countryCode: "MX",
  },
  {
    country: "Nigeria",
    name: "Abuya",
    latitude: 9.0579,
    longitude: 7.4951,
    countryCode: "NG",
  },
  {
    country: "Rusia",
    name: "Moscú",
    latitude: 55.7558,
    longitude: 37.6176,
    countryCode: "RU",
  },
  {
    country: "Arabia Saudita",
    name: "Riad",
    latitude: 24.7136,
    longitude: 46.6753,
    countryCode: "SA",
  },
  {
    country: "Sudáfrica",
    name: "Pretoria",
    latitude: -25.7479,
    longitude: 28.2293,
    countryCode: "ZA",
  },
  {
    country: "Corea del Sur",
    name: "Seúl",
    latitude: 37.5665,
    longitude: 126.978,
    countryCode: "KR",
  },
  {
    country: "España",
    name: "Madrid",
    latitude: 40.4168,
    longitude: -3.7038,
    countryCode: "ES",
  },
  {
    country: "Reino Unido",
    name: "Londres",
    latitude: 51.5074,
    longitude: -0.1278,
    countryCode: "GB",
  },
  {
    country: "Estados Unidos",
    name: "Washington D.C.",
    latitude: 38.9072,
    longitude: -77.0369,
    countryCode: "US",
  },
];

export default citites;
